eCom/ecommerce/carts/urls.py
from django.conf.urls import url, include
from .views import (
        cart_update,
        cart_home
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update')
]

eCom/ecommerce/ecommerce/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from . import settings

from django.contrib import admin
from .views import homePage, contactPage, aboutPage, loginPage, registerPage
from carts.views import cart_home
# from products.views import (
#         ProductListView,
#         product_list_view,
#         ProductDetailView,
#         product_detail_view,
#         ProductFeaturedListView,
#         ProductFeaturedDetailView,
#         ProductDetailSlugView
#         )

urlpatterns = [
    url(r'^home/$', homePage, name='home'),
    url(r'^about/$', aboutPage, name='about'),
    url(r'^contact/$', contactPage, name='contact'),
    url(r'^login/$', loginPage, name='login'),
    url(r'^register/$', registerPage, name='register'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    # url(r'^cart/$', cart_home, name='cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),


    # url(r'^products/$', ProductListView.as_view()),
    # url(r'^products-fbv/$', product_list_view),
    # # url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCom/ecommerce/products/urls.py
from django.conf.urls import url, include
from .views import (
        ProductListView,
        ProductDetailSlugView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

eCom/ecommerce/templates/base/bootstrap4.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

eCom/ecommerce/templates/base/css4.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

eCom/ecommerce/templates/base/js4.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

eCom/ecommerce/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light" id="shadow">
  <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %}eCommerce{% else %} not eCommerce {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home</a>
      </li>
      <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ products_list_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>
<br>
<br>